### PR TITLE
feat(fr): Add french translation

### PR DESCRIPTION
**Pull request by Mara-Li**
I love your plugin, and think to add a translation in my language (french) will be good, so here is it !

### CODE REVIEW

**Comment by Quorafind** [comment]
Thanks!

**Comment by Quorafind** [comment]
LOL, did you see this file? Would you want to translate this either? Because it is all the UI language: https://github.com/Quorafind/Obsidian-Memos/blob/main/src/translations/locale/en.ts

**Comment by Mara-Li** [comment]
Oh yeah, I can do that too!

**Comment by Mara-Li** [comment]
I pushed a new translation ! Hoping the contexte is good.

**Pull request merged**
